### ISSUE TITLE
rdflib.Graph.label() not working in rdflib 6.3.2

### ISSUE THREAD

**Issue by qmj0923** [nju-websoft/NJU_KnowledgeFusionCourseExp#2]
AttributeError: 'Graph' object has no attribute 'label'

https://github.com/nju-websoft/NJU_KnowledgeFusionCourseExp/blob/4140d7f1a8f145639ccc738b62ad7a85a0ca0080/ontology_matching/src/data_input.py#L25-L27

**Comment by yncui-nju** [comment]
尝试用rdflib的5.0.0版本

**Comment by qmj0923** [comment]
5.0.0版本确实可以，非常感谢！
